#!/bin/bash



LSDB=$(ls -A /var/lib/mysql)
LSETC=$(ls -A /etc/mysql)


#Check for ROOT password
if [ "$MYSQL_ROOT_PASSWORD" = "" ];then
        echo "ERROR: Please check password env MYSQL_ROOT_PASSWORD"
        exit 1
fi

#Check for config files
if [ "$LSETC" = "" ];then 

        tar -xzf /opt/mariadb-etc.tgz -C /
fi

#Check for default DB
if [ "$LSDB" = "" ];then
        echo -n "Creando Base de Datos......."
        tar -xzf /opt/mariadb.tgz -C /
        chown -R mysql.mysql /var/lib/mysql
        echo "Ok"
        echo -n "Levantando servicio temporal...." 
        mysqld_safe  2>&1 &
        sleep 8
        echo "Ok"
        echo -n "Configurando password y usuario root........"
        mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED VIA mysql_native_password;"
        mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED BY '$MYSQL_ROOT_PASSWORD';"
        mysql -e "grant all privileges on *.* to 'root'@'%' identified by '$MYSQL_ROOT_PASSWORD' with grant option;"
        killall mysqld
        sleep 8
        echo "Ok"


fi





exec mysqld_safe

